name: Blue Heron Communications
favicon: null
layout_spectrum: 0.5751057197339833
typography_spectrum: 0.23759665642865002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.988945082295686
  lightness: 0.6062807731796056
  saturation: 0.4547783841844648
  rhythmicContrast: 0.7230828749015927
purpose: []
